version: "3"
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file: .docker-development-vars
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
volumes:
  bundle_cache:
